# This is a basic workflow to help you get started with Actions

name: Create Release

# Controls when the workflow will run
on:
  push:
    tags:
      - '*'
      
jobs:
  version:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      - uses: ./.github/workflows/build-typescript
      
      - name: version
        run: echo "::set-output name=version::$(php -r 'echo json_decode(file_get_contents(env("GITHUB_WORKSPACE") . "/composer.json"))->version;')"
        id: version

      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: true
          release_name: ${{ steps.version.outputs.version }}
          tag_name: ${{ github.ref }}
          body_path: CHANGELOG.md
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: upload-compiled-typescript
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.output.upload_url }}
          asset_path: $GITHUB_WORKSPACE/js/equit.js
          asset_name: equit-${{ steps.version.outputs.version }}.js
          asset_content_type: text/javascript

      - name: upload-compiled-typescript-definitions
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.output.upload_url }}
          asset_path: $GITHUB_WORKSPACE/js/equit.d.ts
          asset_name: equit-${{ steps.version.outputs.version }}.d.ts
          asset_content_type: text/javascript
          
